#!/bin/bash -ex

sudo apt remove vim vim-runtime vim-tiny vim-common
sudo apt install ctags nerd-fonts-complete cmake git fzf

git clone https://github.com/vim/vim.git ./tmp
cd tmp/src
./configure --with-features=huge --enable-multibyte --enable-pythoninterp=yes --enable-rubyinterp=yes --enable-python3interp=yes --enable-perlinterp=yes --enable-luainterp=yes --enable-cscope
make
make install
cd ../..
rm -rf tmp

cp vimrc ~/.vimrc
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
cp -r vim ~/.vim

python ~/.vim/plugged/YouCompleteMe/install.py
