vim.cmd("filetype plugin indent on")
vim.cmd("syntax enable")
vim.cmd("let g:vimtex_view_method = 'skim'")
vim.cmd("let g:vimtex_compiler_latexmk_engines = { '_': '-xelatex'}")
vim.cmd("let g:vimtex_quickfix_open_on_warning = 0")
vim.cmd("let g:vimtex_view_enabled = 0")
