#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        1.0            \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add label="^*Save*$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Ghidra$" manage=off

# For working
# yabai -m rule --add app="^Terminal$" space=^1
# yabai -m rule --add app="^Visual Studio Code$" space=^1
# yabai -m rule --add app="^PyCharm$" space=^1
# yabai -m rule --add app="^Eclipse$" space=^1
# yabai -m rule --add app="^Emacs$" space=^1

# For Reading Papers and Note Taking
# yabai -m rule --add app="^Typora$" space=^2
# yabai -m rule --add app="^Obsidian$" space=^2
# yabai -m rule --add app="^Notion$" space=^2
# yabai -m rule --add app="^Feishu$" space=^2
# yabai -m rule --add app="^Zotero$" space=^2

# For entertainment
# yabai -m rule --add app="^Spotify$" space=^3
# yabai -m rule --add app="^Music$" space=^3

# Chatting
# yabai -m rule --add app="^WeChat$" space=^4

yabai -m config window_shadow float
yabai -m config window_opacity off
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.95

yabai -m config external_bar main:30:0

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
